self.addEventListener("install",e=>{
 e.waitUntil(
   caches.open("kas-masjid").then(c=>c.add("index.html"))
 );
});
self.addEventListener("fetch",e=>{
 e.respondWith(
   caches.match(e.request).then(r=>r||fetch(e.request))
 );
});